export interface Theme {
  id: string;
  name: string;
  type: 'dark' | 'light';
  colors: Record<string, string>;
}

export const themes: Theme[] = [
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    type: 'dark',
    colors: {
      '--bg-primary': '#1e1e2e',
      '--bg-secondary': '#181825',
      '--bg-surface': '#313244',
      '--bg-hover': '#45475a',
      '--text-primary': '#cdd6f4',
      '--text-secondary': '#a6adc8',
      '--text-muted': '#6c7086',
      '--accent': '#89b4fa',
      '--accent-hover': '#74c7ec',
      '--border': '#45475a',
      '--success': '#a6e3a1',
      '--warning': '#f9e2af',
      '--error': '#f38ba8',
    },
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    type: 'light',
    colors: {
      '--bg-primary': '#eff1f5',
      '--bg-secondary': '#e6e9ef',
      '--bg-surface': '#ccd0da',
      '--bg-hover': '#bcc0cc',
      '--text-primary': '#4c4f69',
      '--text-secondary': '#5c5f77',
      '--text-muted': '#8c8fa1',
      '--accent': '#1e66f5',
      '--accent-hover': '#209fb5',
      '--border': '#bcc0cc',
      '--success': '#40a02b',
      '--warning': '#df8e1d',
      '--error': '#d20f39',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    type: 'dark',
    colors: {
      '--bg-primary': '#282a36',
      '--bg-secondary': '#21222c',
      '--bg-surface': '#44475a',
      '--bg-hover': '#6272a4',
      '--text-primary': '#f8f8f2',
      '--text-secondary': '#bfbfbf',
      '--text-muted': '#6272a4',
      '--accent': '#bd93f9',
      '--accent-hover': '#ff79c6',
      '--border': '#44475a',
      '--success': '#50fa7b',
      '--warning': '#f1fa8c',
      '--error': '#ff5555',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark Pro',
    type: 'dark',
    colors: {
      '--bg-primary': '#282c34',
      '--bg-secondary': '#21252b',
      '--bg-surface': '#2c313c',
      '--bg-hover': '#3e4451',
      '--text-primary': '#abb2bf',
      '--text-secondary': '#828997',
      '--text-muted': '#5c6370',
      '--accent': '#61afef',
      '--accent-hover': '#56b6c2',
      '--border': '#3e4451',
      '--success': '#98c379',
      '--warning': '#e5c07b',
      '--error': '#e06c75',
    },
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    type: 'dark',
    colors: {
      '--bg-primary': '#0d1117',
      '--bg-secondary': '#010409',
      '--bg-surface': '#161b22',
      '--bg-hover': '#1f2428',
      '--text-primary': '#c9d1d9',
      '--text-secondary': '#8b949e',
      '--text-muted': '#484f58',
      '--accent': '#58a6ff',
      '--accent-hover': '#79c0ff',
      '--border': '#30363d',
      '--success': '#3fb950',
      '--warning': '#d29922',
      '--error': '#f85149',
    },
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    type: 'light',
    colors: {
      '--bg-primary': '#ffffff',
      '--bg-secondary': '#f6f8fa',
      '--bg-surface': '#eaeef2',
      '--bg-hover': '#d0d7de',
      '--text-primary': '#24292f',
      '--text-secondary': '#57606a',
      '--text-muted': '#8c959f',
      '--accent': '#0969da',
      '--accent-hover': '#0550ae',
      '--border': '#d0d7de',
      '--success': '#1a7f37',
      '--warning': '#9a6700',
      '--error': '#cf222e',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    type: 'dark',
    colors: {
      '--bg-primary': '#2e3440',
      '--bg-secondary': '#272c36',
      '--bg-surface': '#3b4252',
      '--bg-hover': '#434c5e',
      '--text-primary': '#eceff4',
      '--text-secondary': '#d8dee9',
      '--text-muted': '#4c566a',
      '--accent': '#88c0d0',
      '--accent-hover': '#81a1c1',
      '--border': '#3b4252',
      '--success': '#a3be8c',
      '--warning': '#ebcb8b',
      '--error': '#bf616a',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    type: 'dark',
    colors: {
      '--bg-primary': '#002b36',
      '--bg-secondary': '#00212b',
      '--bg-surface': '#073642',
      '--bg-hover': '#094855',
      '--text-primary': '#839496',
      '--text-secondary': '#657b83',
      '--text-muted': '#586e75',
      '--accent': '#268bd2',
      '--accent-hover': '#2aa198',
      '--border': '#073642',
      '--success': '#859900',
      '--warning': '#b58900',
      '--error': '#dc322f',
    },
  },
];
